README.md
_config.yml
_data/menu.yml
_includes/nav.html
_layouts/default.html
assets/css/style.scss

- Added preliminar changes to setup dynamic navigation to gh-pages branch

APOLLO-13615: Add preliminar dynamic navigation to gh-pages

---

demo/build.sh
java-sdk/connectors/build.gradle
java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentConfig.java
java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentFetcher.java
java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentPlugin.java

- Update random connector to support new SDK schema

APOLLO-13836: Update random connector to support new SDK schema

---

demo/build.sh
java-sdk/connectors/build.gradle

- Cherry-pick of 624a2e30907a62769cefac3f7113245e25e17a1d and  ac230b20293214001e080d31bc41776b4ce257eb to 4.0.x
- Add script to build demo plugin
- Rename zip name in  `java-sdk/connectors/build.gradle`
- Not hardcode random version in script demo/build.sh
- From local repository connectors-sdk-resources, run the build script i.e. :
```
connectors-sdk-resources$ ./demo/build.sh master <my path to fusion> <my fusion version> <my path targeth>
```
- the random connector generated  has not the random version `random-connector.zip`

APOLLO-14069: Add script demo/build.sh

---

java-sdk/README_security_filtering.md
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/SecurityFilteringPlugin.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/security/SecurityFilteringSecurityFilterComponent.java

- Add missing section for SecurityFilterComponent

APOLLO-19721: Add missing section for SecurityFilterComponent

---

java-sdk/connectors/gradle.properties
java-sdk/connectors/random-connector/README.asciidoc
java-sdk/connectors/security-filtering-connector/README.md

APOLLO-20314 4.2.1

---

java-sdk/connectors/gradle.properties

APOLLO-20314 4.2.2

---

java-sdk/connectors/gradle.properties

APOLLO-20314 4.2.3

---

java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentFetcher.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/SecurityFilteringPlugin.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/fetcher/SecurityFilteringAccessControlFetcher.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/fetcher/SecurityFilteringContentFetcher.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/validation/SecurityFilteringValidationComponent.java

Fixed number of permissions on groups

APOLLO-20394: Fixed number of permissions on groups

---

java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentFetcher.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/SecurityFilteringPlugin.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/fetcher/SecurityFilteringAccessControlFetcher.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/fetcher/SecurityFilteringContentFetcher.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/security/SecurityFilteringSecurityFilterComponent.java
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/fusion/connector/plugin/validation/SecurityFilteringValidationComponent.java

- Update security filtering connector to use new security filtering approach

APOLLO-20558: Update security filtering connector

---

java-sdk/connectors/gradle.properties

- Upgrade connectors-sdk-version - Fusion release 4.2.4

APOLLO-21017 - Fusion release 4.2.4

---

README.asciidoc

APOLLO-17514 crawl db fields

---

java-sdk/connectors/random-connector-incremental/.gitignore
java-sdk/connectors/random-connector-incremental/README.md
java-sdk/connectors/random-connector-incremental/build.gradle
java-sdk/connectors/random-connector-incremental/gradle.properties
java-sdk/connectors/random-connector-incremental/src/main/java/com/lucidworks/fusion/connector/plugin/RandomIncrementalPlugin.java
java-sdk/connectors/random-connector-incremental/src/main/java/com/lucidworks/fusion/connector/plugin/config/RandomIncrementalConfig.java
java-sdk/connectors/random-connector-incremental/src/main/java/com/lucidworks/fusion/connector/plugin/fetcher/RandomInContentIncrementalFetcher.java
java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentFetcher.java
java-sdk/connectors/settings.gradle

- Added a random-connector-incremental
- See [README](https://github.com/lucidworks/connectors-sdk-resources/blob/30e453a056d706ffd3f085964630c39e9ae87239/java-sdk/connectors/random-connector-incremental/README.md) file

APOLLO-20775: Add a random-connector-incremental

---

java-sdk/connectors/random-connector-incremental/.gitignore
java-sdk/connectors/random-connector-incremental/README.md
java-sdk/connectors/random-connector-incremental/build.gradle
java-sdk/connectors/random-connector-incremental/gradle.properties
java-sdk/connectors/random-connector-incremental/src/main/java/com/lucidworks/fusion/connector/plugin/RandomIncrementalPlugin.java
java-sdk/connectors/random-connector-incremental/src/main/java/com/lucidworks/fusion/connector/plugin/config/RandomIncrementalConfig.java
java-sdk/connectors/random-connector-incremental/src/main/java/com/lucidworks/fusion/connector/plugin/fetcher/RandomInContentIncrementalFetcher.java
java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentFetcher.java
java-sdk/connectors/settings.gradle

- Added a random-connector-incremental
- See [README](https://github.com/lucidworks/connectors-sdk-resources/blob/30e453a056d706ffd3f085964630c39e9ae87239/java-sdk/connectors/random-connector-incremental/README.md) file

APOLLO-20775: Add a random-connector-incremental - 4.2.x

---

java-sdk/connectors/build.gradle

APOLLO-21340: update group id

---

java-sdk/connectors/README.md

add some info how to deploy connector

add deploy info

---

README.asciidoc

Added Connectors SDK support matrix 
APOLLO-23821: matrix version

APOLLO-23821: matrix version

---

java-sdk/configuration.asciidoc

Based on suggestions from Matt Mitchell , re-added about schema. Removed "get" references

APOLLO -24186 Part 2-Re-added About schema section

---

README.asciidoc

Documentation regarding server side processing of sdk items.

APOLLO-24180: docs regarding server side processing

---

README.asciidoc
java-sdk/connectors/gradle.properties

APOLLO-24672: update the matrix version.

APOLLO-24672: add new entry in matrix version.

---

java-sdk/README_security_filtering.md

Added some explicit text regarding case matching of the User ID used in the join

APOLLO-25529 - Add text on case sensitivity for ACLs

---

java-sdk/connectors/feed-connector/README.md

Added migration steps to upgrade feed connector from 2.0.0 or earlier version to 2.0.1

APOLLO-25091 Update README with SDK 2.0.1 changes to the deletion of stray items

---

java-sdk/connectors/README.md

Added a sentence on building to a specific SDK version

Added info regarding targeting the SDK version

---

README.asciidoc
java-sdk/configuration.asciidoc
java-sdk/connectors/feed-connector/gradle.properties
java-sdk/connectors/gradle.properties
java-sdk/connectors/incremental-connector/README.md

APOLLO-26114
* Updated the support version matrix with the next release.
* Remove out of date documentation from configuration.asciidoc
* Updated the connectors SDK Version to 2.0.2

APOLLO-26114: support version matrix

---

java-sdk/README.asciidoc

APOLLO-24299: added proper item state table

APOLLO-24299: added proper item state table

---

java-sdk/connectors/simple-connector/README.asciidoc

APOLLO-29024: Fix the order of the number on the list.

APOLLO-29024-fix-numbers

---

README.asciidoc
java-sdk/connectors/gradle.properties

APOLLO-29646: update sdk version

APOLLO-29646: update sdk version

---

README.asciidoc

Version for docs SDK- 400

---

README.asciidoc

version-for-docs-300

---

README.asciidoc

version-for-docs-203

---

README.asciidoc

Version for docs 203

---

README.asciidoc

Version for docs 130

---

README.asciidoc

Version for docs 140

---

README.asciidoc

Version for docs 150

---

README.asciidoc

Version for docs 200

---

README.asciidoc

Version for docs 201

---

README.asciidoc

version-for-docs-120

---

README.asciidoc

version-for-docs-110

---

README.asciidoc

Version for docs 202

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/security.asciidoc

Doc edits 400

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/security.asciidoc

Fix link for the 4.0.0 version

Fix link for the 4.0.0 version

---

java-sdk/README.asciidoc
java-sdk/connectors/README.md
java-sdk/connectors/simple-connector/README.asciidoc

Fix documentation links for 4.0.0

Fix documentation links for 4.0.0

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/connectors/README.md
java-sdk/connectors/simple-connector/README.asciidoc
java-sdk/security.asciidoc

Fix documentation links for 3.0.0

Fix documentation links for 3.0.0

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/connectors/README.md
java-sdk/connectors/simple-connector/README.asciidoc
java-sdk/security.asciidoc

Fix documentation links for 2.0.3

Fix documentation links for 2.0.3

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/connectors/README.md
java-sdk/connectors/simple-connector/README.asciidoc
java-sdk/security.asciidoc

Fix documentation links for 2.0.2

Fix documentation links for 2.0.2

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/connectors/README.md
java-sdk/connectors/simple-connector/README.asciidoc
java-sdk/security.asciidoc

Fix Doc links 2.0.1

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/connectors/README.md
java-sdk/connectors/random-connector/README.asciidoc
java-sdk/security.asciidoc

Fix links of 2.0.0 version

---

README.asciidoc
java-sdk/README.asciidoc
java-sdk/connectors/README.md
java-sdk/connectors/random-connector/README.asciidoc
java-sdk/security.asciidoc

Fix documentation in 1.5.0

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-311: Update documentation and gradle.properties.

---

java-sdk/connectors/build.gradle
java-sdk/connectors/feed-connector/src/main/java/com/lucidworks/connector/plugins/feed/fetcher/FeedFetcher.java
java-sdk/connectors/imap-connector/src/main/java/com/lucidworks/connector/plugins/imap/ImapFetcher.java
java-sdk/connectors/incremental-connector/src/main/java/com/lucidworks/connector/plugins/incremental/fetcher/IncrementalContentFetcher.java
java-sdk/connectors/simple-connector/src/main/java/com/lucidworks/connector/plugins/random/fetcher/RandomContentFetcher.java

- Group together  all the connector Gradle tasks and add description.
- Fix all deprecated example code

FUS 352 improve examples and doc

---

README.asciidoc

FUS-480: update support matrix

---

README.asciidoc

FUS-702: Update sdk matrix

---

README.asciidoc

FUS-835: Update sdk matrix

---

README.asciidoc

- Update sdk matrix
https://github.com/lucidworks/connectors-sdk-resources/blob/2dc1604b513ff337183de6df5381dda9e0c8db66/README.asciidoc

FUS-972: Update sdk matrix

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-1876: Update sdk matrix

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-2192: Update sdk resources

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-2393: Update sdk resources

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-2908: Update SDK resources

---

README.asciidoc
java-sdk/connectors/gradle.properties

Update connectors-sdk resources

FUS-3565, FUS-3563: Update connectors-sdk resources

---

README.asciidoc

- Update connector-sdk-resources

FUS-3835: Update connector-sdk-resources

---

README.asciidoc

FUS-3989: update sdk matrix

---

java-sdk/connectors/gradle.properties

FUS-3989: Update gradle.properties

FUS-3989: Update gradle.properties

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-2943: Update readme files

---

README.asciidoc

FUS-2943: Expand the range of Fusion version in the Support Matrix

FUS-2943: Expand the range of Fusion version in the Support Matrix

---

java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/connector/plugins/security/fetcher/SecurityFilteringAccessControlFetcher.java

Fix the example to comply with FUS-4040

FUS-4244: Fix security trimming example

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-3691: Update readme files

---

README.asciidoc
java-sdk/connectors/gradle.properties

FUS-4304: Update readme files

---

java-sdk/connectors/security-filtering-connector/README.md
java-sdk/connectors/security-filtering-connector/src/main/java/com/lucidworks/connector/plugins/security/fetcher/SecurityFilteringAccessControlFetcher.java

Update the filter-security-demo plugin:
- Set properly the acls to documents (use .withAcls).
- Add test cases to validate support for denyAcls is working

FUS-5685: Update the filter-security-demo plugin

---

README.asciidoc

Update connectorsSDK Support Matrix, relate each fusion version with the supported connectorsSDK

DAAC-336: Update connectorsSDK Support Matrix
